CREATE TABLE `injectable_requests` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `medical_record_id` INTEGER NOT NULL,
    `patient_id` INTEGER NOT NULL,
    `injectable_id` INTEGER NOT NULL,
    `name` VARCHAR(160) NOT NULL,
    `category` ENUM('VITAMINAS', 'PROTOCOLOS', 'IMUNIDADES') NOT NULL,
    `route` ENUM('IM', 'EV', 'SC') NOT NULL,
    `sessions` INTEGER NOT NULL DEFAULT 1,
    `status` ENUM('AGUARDANDO_APLICACAO') NOT NULL DEFAULT 'AGUARDANDO_APLICACAO',
    `requested_by_id` INTEGER NOT NULL,
    `requested_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    INDEX `injectable_requests_patient_id_idx`(`patient_id`),
    INDEX `injectable_requests_requested_by_id_idx`(`requested_by_id`),
    UNIQUE INDEX `injectable_requests_medical_record_id_injectable_id_key`(`medical_record_id`, `injectable_id`),
    PRIMARY KEY (`id`),
    CONSTRAINT `injectable_requests_medical_record_id_fkey` FOREIGN KEY (`medical_record_id`) REFERENCES `medical_records` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `injectable_requests_patient_id_fkey` FOREIGN KEY (`patient_id`) REFERENCES `patients` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `injectable_requests_injectable_id_fkey` FOREIGN KEY (`injectable_id`) REFERENCES `injectables` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `injectable_requests_requested_by_id_fkey` FOREIGN KEY (`requested_by_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
