import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, Building2, CheckCircle2, ChevronRight, CircleDollarSign, ClipboardList, LogOut, Menu, Pencil, Plus, ShieldCheck, Stethoscope, Trash2, UserRound, Users, X } from 'lucide-react';
import './styles.css';

type Profile = 'ADMINISTRADOR' | 'MEDICO' | 'SECRETARIA';
type ModuleKey = 'overview' | 'users' | 'clinic' | 'doctors' | 'insurances' | 'procedures';
type Row = Record<string, any>;
const API = import.meta.env.VITE_API_URL || 'http://localhost:3333/api';

const modules: { key: ModuleKey; label: string; icon: React.ReactNode; singular: string }[] = [
  { key: 'users', label: 'Usuários', singular: 'usuário', icon: <Users size={18}/> },
  { key: 'clinic', label: 'Clínica', singular: 'clínica', icon: <Building2 size={18}/> },
  { key: 'doctors', label: 'Médicos', singular: 'médico', icon: <Stethoscope size={18}/> },
  { key: 'insurances', label: 'Convênios', singular: 'convênio', icon: <ShieldCheck size={18}/> },
  { key: 'procedures', label: 'Procedimentos', singular: 'procedimento', icon: <ClipboardList size={18}/> }
];

async function request(path: string, options: RequestInit = {}) { const token = localStorage.getItem('medclinic_token'); const res = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options.headers || {}) } }); if (!res.ok) { const e = await res.json().catch(() => ({})); throw new Error(e.message || 'Não foi possível concluir a operação.'); } return res.status === 204 ? null : res.json(); }
const money = (value: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(value || 0));

function Login({ onLogin }: { onLogin: (data: any) => void }) { const [login, setLogin] = useState('theomar_rego@hotmail'); const [password, setPassword] = useState('123456'); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); setLoading(true); setError(''); try { const data = await request('/auth/login', { method: 'POST', body: JSON.stringify({ login, password }) }); localStorage.setItem('medclinic_token', data.token); onLogin(data.user); } catch (err: any) { setError(err.message); } finally { setLoading(false); } }
  return <main className="login-page"><div className="login-art"><div className="brand-mark"><Activity size={25}/></div><p className="eyebrow">INTIMAVIE · GESTÃO CLÍNICA</p><h1>Cuidado organizado.<br/><em>Gestão inteligente.</em></h1><p className="muted light">Uma visão clara para cada decisão do seu dia clínico.</p><div className="login-metric"><span>MedClinic CRM</span><strong>Atendimento com precisão</strong></div></div><div className="login-card"><div className="mobile-brand"><Activity size={21}/><strong>MedClinic</strong></div><p className="eyebrow">ACESSO RESTRITO</p><h2>Bem-vindo de volta</h2><p className="muted">Entre no ambiente administrativo da Intimavie.</p><form onSubmit={submit}><label>Login<input value={login} onChange={e=>setLogin(e.target.value)} autoComplete="username"/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label>{error && <div className="error">{error}</div>}<button className="primary full" disabled={loading}>{loading ? 'Entrando…' : 'Entrar no sistema'}<ChevronRight size={18}/></button></form><small>Ambiente interno protegido · MedClinic v1.0</small></div></main>
}

function App() { const [user, setUser] = useState<any>(null); const [module, setModule] = useState<ModuleKey>('overview'); const [mobileMenu, setMobileMenu] = useState(false); useEffect(() => { if (localStorage.getItem('medclinic_token')) request('/auth/me').then(setUser).catch(() => localStorage.removeItem('medclinic_token')); }, []); if (!user) return <Login onLogin={setUser}/>;
  function logout() { localStorage.removeItem('medclinic_token'); setUser(null); }
  return <div className="shell"><aside className={mobileMenu ? 'sidebar open' : 'sidebar'}><div className="brand"><div className="brand-mark"><Activity size={21}/></div><div><strong>MedClinic</strong><span>INTIMAVIE</span></div></div><div className="nav-group"><span className="nav-caption">VISÃO GERAL</span><button className={module === 'overview' ? 'nav-item active' : 'nav-item'} onClick={()=>{setModule('overview');setMobileMenu(false)}}><Activity size={18}/> Dashboard</button></div><div className="nav-group"><span className="nav-caption">ADMINISTRAÇÃO</span>{modules.map(item=><button key={item.key} className={module === item.key ? 'nav-item active' : 'nav-item'} onClick={()=>{setModule(item.key);setMobileMenu(false)}}>{item.icon}{item.label}</button>)}</div><div className="sidebar-footer"><div className="secure"><ShieldCheck size={16}/><span>Ambiente protegido<br/><b>Dados criptografados</b></span></div></div></aside><div className="content"><header className="topbar"><button className="icon-button menu" onClick={()=>setMobileMenu(!mobileMenu)}><Menu size={20}/></button><div className="breadcrumb">Intimavie <ChevronRight size={14}/> <strong>{module === 'overview' ? 'Dashboard' : modules.find(m=>m.key===module)?.label}</strong></div><div className="top-actions"><span className="date">28 de setembro de 2026</span><div className="avatar">{user.fullName?.split(' ').map((x:string)=>x[0]).slice(0,2).join('')}</div><div className="user-name"><strong>{user.fullName}</strong><span>Administrador</span></div><button className="icon-button" onClick={logout} title="Sair"><LogOut size={18}/></button></div></header><main className="main">{module === 'overview' ? <Dashboard setModule={setModule}/> : <CrudPage module={module}/>}</main></div></div>
}

function Dashboard({ setModule }: { setModule: (m: ModuleKey)=>void }) { const cards = [{ label:'Usuários ativos', value:'—', icon:<Users/>, key:'users' as ModuleKey, tone:'blue' },{label:'Médicos cadastrados',value:'—',icon:<Stethoscope/>,key:'doctors' as ModuleKey,tone:'teal'},{label:'Convênios ativos',value:'—',icon:<ShieldCheck/>,key:'insurances' as ModuleKey,tone:'gold'},{label:'Procedimentos',value:'—',icon:<ClipboardList/>,key:'procedures' as ModuleKey,tone:'purple'}]; return <><div className="page-heading"><div><p className="eyebrow">SEGUNDA-FEIRA, 28 SET 2026</p><h1>Bom dia, administrador.</h1><p className="muted">Acompanhe os cadastros essenciais da sua clínica.</p></div><button className="primary" onClick={()=>setModule('clinic')}><Building2 size={17}/> Configurar clínica</button></div><div className="cards">{cards.map(c=><button className="stat-card" key={c.key} onClick={()=>setModule(c.key)}><span className={`stat-icon ${c.tone}`}>{c.icon}</span><span className="stat-label">{c.label}</span><strong>{c.value}</strong><span className="stat-link">Gerenciar <ChevronRight size={14}/></span></button>)}</div><div className="welcome-panel"><div><span className="panel-kicker"><CheckCircle2 size={16}/> SISTEMA OPERACIONAL</span><h2>Seu centro de gestão clínica</h2><p>Comece configurando os dados da clínica e cadastre sua equipe, convênios e procedimentos.</p></div><div className="panel-illustration"><div className="orb orb-a"/><div className="orb orb-b"/><Activity size={46}/></div></div><div className="quick-grid"><button onClick={()=>setModule('users')}><span><UserRound size={18}/></span><div><strong>Equipe e acessos</strong><small>Gerencie usuários e perfis</small></div><ChevronRight/></button><button onClick={()=>setModule('doctors')}><span><Stethoscope size={18}/></span><div><strong>Corpo clínico</strong><small>Cadastre médicos e especialidades</small></div><ChevronRight/></button></div></> }

const configs: Record<Exclude<ModuleKey,'overview'|'clinic'>, {path:string; title:string; fields:{key:string;label:string;type?:string;options?:string[]}[]; columns:{key:string;label:string;format?:(v:any)=>string}[]}> = {
 users:{path:'users',title:'Usuários',fields:[{key:'fullName',label:'Nome completo'},{key:'login',label:'Login'},{key:'password',label:'Senha',type:'password'},{key:'profile',label:'Perfil',type:'select',options:['ADMINISTRADOR','MEDICO','SECRETARIA']}],columns:[{key:'fullName',label:'Nome completo'},{key:'login',label:'Login'},{key:'profile',label:'Perfil'}]},
 doctors:{path:'doctors',title:'Médicos',fields:[{key:'fullName',label:'Nome completo'},{key:'crm',label:'CRM'},{key:'rqe',label:'RQE'},{key:'specialty',label:'Especialidade'}],columns:[{key:'fullName',label:'Nome completo'},{key:'crm',label:'CRM'},{key:'rqe',label:'RQE'},{key:'specialty',label:'Especialidade'}]},
 insurances:{path:'insurances',title:'Convênios',fields:[{key:'name',label:'Nome'},{key:'ans',label:'ANS'},{key:'value',label:'Valor',type:'number'},{key:'active',label:'Ativo',type:'checkbox'}],columns:[{key:'name',label:'Nome'},{key:'ans',label:'ANS'},{key:'value',label:'Valor',format:money},{key:'active',label:'Status',format:(v)=>v?'Ativo':'Inativo'}]},
 procedures:{path:'procedures',title:'Procedimentos',fields:[{key:'name',label:'Nome'},{key:'value',label:'Valor',type:'number'},{key:'active',label:'Ativo',type:'checkbox'}],columns:[{key:'name',label:'Nome'},{key:'value',label:'Valor',format:money},{key:'active',label:'Status',format:(v)=>v?'Ativo':'Inativo'}]}
};
function CrudPage({module}:{module:ModuleKey}) { if (module === 'clinic') return <ClinicPage/>; const config = configs[module as keyof typeof configs]; const [rows,setRows]=useState<Row[]>([]); const [editing,setEditing]=useState<Row|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); async function load(){setLoading(true);try{setRows(await request(`/admin/${config.path}`) || [])}catch(e:any){setError(e.message)}finally{setLoading(false)}} useEffect(()=>{load()},[module]); async function save(data:Row){try{await request(`/admin/${config.path}${editing?`/${editing.id}`:''}`,{method:editing?'PUT':'POST',body:JSON.stringify(data)});setEditing(null);load()}catch(e:any){setError(e.message)}} async function remove(id:number){if(!confirm('Excluir este cadastro?'))return;try{await request(`/admin/${config.path}/${id}`,{method:'DELETE'});load()}catch(e:any){setError(e.message)}} return <><div className="page-heading"><div><p className="eyebrow">ADMINISTRAÇÃO</p><h1>{config.title}</h1><p className="muted">Cadastre e mantenha os dados atualizados.</p></div><button className="primary" onClick={()=>setEditing({active:true})}><Plus size={17}/> Novo {config.title.slice(0,-1)}</button></div>{error&&<div className="error page-error">{error}</div>}<div className="table-card"><div className="table-head"><strong>{rows.length} cadastro{rows.length===1?'':'s'}</strong><span className="muted">Última atualização agora</span></div>{loading?<div className="empty">Carregando…</div>:rows.length===0?<div className="empty"><ClipboardList size={28}/><strong>Nenhum cadastro ainda</strong><span>Adicione o primeiro registro usando o botão acima.</span></div>:<div className="table-scroll"><table><thead><tr>{config.columns.map(c=><th key={c.key}>{c.label}</th>)}<th></th></tr></thead><tbody>{rows.map(row=><tr key={row.id}>{config.columns.map(c=><td key={c.key}>{c.key==='active'?<span className={row[c.key]?'status active':'status'}>{c.format?.(row[c.key])}</span>:c.format?c.format(row[c.key]):row[c.key]}</td>)}<td className="row-actions"><button onClick={()=>setEditing(row)} title="Editar"><Pencil size={16}/></button><button onClick={()=>remove(row.id)} title="Excluir"><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>}</div>{editing&&<Modal title={`${editing.id?'Editar':'Novo'} ${config.title.slice(0,-1)}`} fields={config.fields} initial={editing} onClose={()=>setEditing(null)} onSave={save}/>}</> }

function ClinicPage(){const [data,setData]=useState<Row>({});const [loading,setLoading]=useState(true);const [saved,setSaved]=useState(false);useEffect(()=>{request('/admin/clinic').then(x=>setData(x||{})).finally(()=>setLoading(false))},[]);async function save(e:React.FormEvent){e.preventDefault();await request('/admin/clinic',{method:'PUT',body:JSON.stringify(data)});setSaved(true);setTimeout(()=>setSaved(false),2500)}return <><div className="page-heading"><div><p className="eyebrow">ADMINISTRAÇÃO</p><h1>Clínica</h1><p className="muted">Informações institucionais da Intimavie.</p></div>{saved&&<div className="success"><CheckCircle2 size={17}/> Dados salvos</div>}</div><form className="form-card" onSubmit={save}><div className="form-title"><span className="stat-icon blue"><Building2 size={20}/></span><div><h3>Dados da clínica</h3><p className="muted">Essas informações aparecem nos documentos do sistema.</p></div></div><div className="form-grid"><label>Razão social<input value={data.legalName||''} onChange={e=>setData({...data,legalName:e.target.value})}/></label><label>Nome fantasia<input value={data.tradeName||''} onChange={e=>setData({...data,tradeName:e.target.value})}/></label><label>CNPJ<input value={data.cnpj||''} onChange={e=>setData({...data,cnpj:e.target.value})}/></label><label>CNAE<input value={data.cnae||''} onChange={e=>setData({...data,cnae:e.target.value})}/></label><label className="wide">Endereço<textarea rows={4} value={data.address||''} onChange={e=>setData({...data,address:e.target.value})}/></label></div><div className="form-footer"><span className="muted">Campos obrigatórios</span><button className="primary" disabled={loading}>Salvar alterações</button></div></form></>}

function Modal({title,fields,initial,onClose,onSave}:{title:string;fields:any[];initial:Row;onClose:()=>void;onSave:(d:Row)=>void}){const [data,setData]=useState<Row>(initial);return <div className="modal-backdrop"><div className="modal"><div className="modal-header"><div><p className="eyebrow">CADASTRO</p><h2>{title}</h2></div><button className="icon-button" onClick={onClose}><X size={19}/></button></div><div className="modal-fields">{fields.map(f=><label key={f.key} className={f.type==='checkbox'?'check-label':''}>{f.type==='checkbox'?<><input type="checkbox" checked={data[f.key] ?? true} onChange={e=>setData({...data,[f.key]:e.target.checked})}/>{f.label}</>:<>{f.label}{f.type==='select'?<select value={data[f.key]||''} onChange={e=>setData({...data,[f.key]:e.target.value})}><option value="">Selecione…</option>{f.options.map((o:string)=><option key={o} value={o}>{o}</option>)}</select>:<input type={f.type||'text'} value={data[f.key]||''} onChange={e=>setData({...data,[f.key]:f.type==='number'?Number(e.target.value):e.target.value})}/>}</>}</label>)}</div><div className="modal-footer"><button className="secondary" onClick={onClose}>Cancelar</button><button className="primary" onClick={()=>onSave(data)}>Salvar cadastro</button></div></div></div>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
