import React, { useEffect, useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight, Plus } from 'lucide-react';
import type { Row } from '../lib/app';
import { money, request } from '../lib/app';
import { AppointmentModal } from './AppointmentModal';
export function AppointmentsPage({user}:{user:any}) {
  const canManage=user.profile==='ADMINISTRADOR'||user.profile==='SECRETARIA';
  const today=new Date(); const localDate=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  const [date,setDate]=useState(localDate(today)); const [rows,setRows]=useState<Row[]>([]); const [meta,setMeta]=useState<any>({patients:[],doctors:[],insurances:[],attendances:[],procedures:[]}); const [editing,setEditing]=useState<Row|null>(null); const [modalOpen,setModalOpen]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const slots=useMemo(()=>Array.from({length:25},(_,i)=>`${String(8+Math.floor(i/2)).padStart(2,'0')}:${i%2?'30':'00'}`),[]);
  const isToday=date===localDate(today);
  const weekday=new Date(`${date}T12:00:00`).toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'});
  async function load(){setLoading(true);setError('');try{const [day,metadata]=await Promise.all([request(`/appointments?date=${date}`), meta.patients.length?Promise.resolve(meta):request('/appointments/meta')]);setRows(day||[]);if(!meta.patients.length)setMeta(metadata)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[date]);
  function openNew(time:string){setEditing({appointmentDate:date,scheduledTime:time,status:'AGENDADO',itemType:'ATENDIMENTO'});setModalOpen(true)}
  function openEdit(row:Row){setEditing(row);setModalOpen(true)}
  function navigateDate(days:number){const next=new Date(`${date}T12:00:00`);next.setDate(next.getDate()+days);setDate(localDate(next))}
  function goToday(){setDate(localDate(new Date()))}
  async function save(data:Row){try{const payload={...data,appointmentDate:date,patientId:Number(data.patientId),doctorId:Number(data.doctorId),insuranceId:Number(data.insuranceId),attendanceId:data.itemType==='ATENDIMENTO'?Number(data.attendanceId):null,procedureId:data.itemType==='PROCEDIMENTO'?Number(data.procedureId):null};await request(`/appointments${editing?.id?`/${editing.id}`:''}`,{method:editing?.id?'PUT':'POST',body:JSON.stringify(payload)});setModalOpen(false);setEditing(null);load()}catch(e:any){setError(e.message)}}
  async function remove(id:number){if(!confirm('Excluir este agendamento?'))return;try{await request(`/appointments/${id}`,{method:'DELETE'});load()}catch(e:any){setError(e.message)}}
  const byTime=(time:string)=>rows.filter(x=>x.scheduledTime===time);
  return <><div className="page-heading"><div><p className="eyebrow">AGENDA CLÍNICA</p><h1>Agendamentos</h1><p className="muted">{weekday[0].toUpperCase()+weekday.slice(1)} · horários de 08:00 a 20:00</p></div>{canManage&&<button className="primary" onClick={()=>openNew('08:00')}><Plus size={17}/> Novo agendamento</button>}</div>{error&&<div className="error page-error">{error}</div>}<div className="agenda-toolbar"><div className="agenda-date-controls"><button className="agenda-nav-button" onClick={()=>navigateDate(-1)} title="Dia anterior"><ChevronLeft size={17}/></button><label>Dia<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="agenda-nav-button" onClick={()=>navigateDate(1)} title="Próximo dia"><ChevronRight size={17}/></button><button className="today-button" onClick={goToday} disabled={isToday}>Hoje</button></div></div><div className="table-card agenda-card"><div className="table-head"><strong>{loading?'Carregando…':`${rows.length} agendamento${rows.length===1?'':'s'}`}</strong><span className="muted">{canManage?'Clique em um horário livre para agendar':'Lista do dia'}</span></div>{!loading&&<div className="agenda-grid">{slots.map(time=><div className="agenda-row" key={time}><div className="agenda-time">{time}</div><div className="agenda-slots">{byTime(time).map(row=><div className={`appointment-chip ${row.status.toLowerCase()}`} key={row.id} onClick={()=>canManage&&openEdit(row)}><strong>{row.patient?.fullName}</strong><span>{row.doctor?.fullName}</span><small>{row.itemType==='PROCEDIMENTO'?row.procedure?.name:row.attendance?.name} · {row.insurance?.name}</small>{canManage&&<button onClick={e=>{e.stopPropagation();remove(row.id)}} title="Excluir">×</button>}</div>)}{canManage&&byTime(time).length===0&&<button className="slot-empty" onClick={()=>openNew(time)}>+ Agendar neste horário</button>}</div></div>)}</div>}</div>{modalOpen&&<AppointmentModal initial={editing||{}} meta={meta} date={date} onClose={()=>{setModalOpen(false);setEditing(null)}} onSave={save}/>}</>
}
