CREATE TABLE `appointments` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `appointment_date` DATE NOT NULL,
  `scheduled_time` VARCHAR(5) NOT NULL,
  `patient_id` INTEGER NOT NULL,
  `doctor_id` INTEGER NOT NULL,
  `insurance_id` INTEGER NOT NULL,
  `item_type` ENUM('ATENDIMENTO', 'PROCEDIMENTO') NOT NULL,
  `attendance_id` INTEGER NULL,
  `procedure_id` INTEGER NULL,
  `status` ENUM('AGENDADO', 'CONFIRMADO', 'ATENDIDO', 'FALTOU') NOT NULL DEFAULT 'AGENDADO',
  `notes` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `appointments_doctor_id_appointment_date_scheduled_time_key` (`doctor_id`, `appointment_date`, `scheduled_time`),
  INDEX `appointments_appointment_date_scheduled_time_idx` (`appointment_date`, `scheduled_time`),
  INDEX `appointments_patient_id_appointment_date_idx` (`patient_id`, `appointment_date`),
  INDEX `appointments_patient_id_fkey` (`patient_id`),
  INDEX `appointments_insurance_id_fkey` (`insurance_id`),
  INDEX `appointments_attendance_id_fkey` (`attendance_id`),
  INDEX `appointments_procedure_id_fkey` (`procedure_id`),
  CONSTRAINT `appointments_patient_id_fkey` FOREIGN KEY (`patient_id`) REFERENCES `patients` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `appointments_doctor_id_fkey` FOREIGN KEY (`doctor_id`) REFERENCES `doctors` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `appointments_insurance_id_fkey` FOREIGN KEY (`insurance_id`) REFERENCES `insurances` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `appointments_attendance_id_fkey` FOREIGN KEY (`attendance_id`) REFERENCES `attendances` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `appointments_procedure_id_fkey` FOREIGN KEY (`procedure_id`) REFERENCES `procedures` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
